# Generated by Django 6.0.1 on 2026-01-31 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('phone1', models.CharField(max_length=20, verbose_name='Teléfono 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Teléfono 2')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_type', models.CharField(choices=[('monthly', 'Mensual'), ('airbnb', 'Airbnb'), ('daily', 'Diario')], max_length=100, verbose_name='Tipo de arriendo')),
                ('check_in', models.DateField(verbose_name='Fecha de entrada')),
                ('check_out', models.DateField(verbose_name='Fecha de salida')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('people_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de personas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(db_column='id_property', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='properties.property')),
                ('tenant', models.ForeignKey(db_column='id_tenant', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.tenant')),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
                'db_table': 'rental',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(db_column='depositAmount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de depósito')),
                ('is_refundable', models.BooleanField(db_column='is_refundable', default=True, verbose_name='Es reembolsable')),
                ('url_files', models.URLField(blank=True, db_column='urlFiles', verbose_name='URL de archivos')),
                ('rental', models.ForeignKey(db_column='id_rental', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Arriendo Mensual',
                'verbose_name_plural': 'Arriendos Mensuales',
                'db_table': 'monthly_rental',
            },
        ),
        migrations.CreateModel(
            name='AirbnbRental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(db_column='is_paid(bool)', default=False, verbose_name='Está pagado')),
                ('rental', models.ForeignKey(db_column='id_rental', on_delete=django.db.models.deletion.CASCADE, related_name='airbnb_records', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Arriendo Airbnb',
                'verbose_name_plural': 'Arriendos Airbnb',
                'db_table': 'airbnb_rental',
            },
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_location', models.CharField(max_length=255, verbose_name='Lugar de pago')),
                ('date', models.DateField(verbose_name='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('voucher_url', models.URLField(blank=True, db_column='voucher_url', verbose_name='URL del comprobante')),
                ('payment_method', models.ForeignKey(db_column='id_paymentMethod', on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Método de pago')),
                ('rental', models.ForeignKey(db_column='id_rental', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Pago de Arriendo',
                'verbose_name_plural': 'Pagos de Arriendos',
                'db_table': 'rental_payment',
                'ordering': ['-date'],
            },
        ),
    ]
