# Generated by Django 5.2.5 on 2026-01-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('disponible', 'Disponible')], default='ocupada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_location',
            field=models.CharField(choices=[('oficina', 'Oficina'), ('daycare', 'DayCare')], max_length=255, verbose_name='Lugar de pago'),
        ),
    ]
