# Generated by Django 6.0.1 on 2026-02-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrental',
            name='url_files',
            field=models.FileField(blank=True, db_column='urlFiles', upload_to='', verbose_name='URL de archivos'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='voucher_url',
            field=models.FileField(blank=True, db_column='voucher_url', upload_to='', verbose_name='URL del comprobante'),
        ),
    ]
