# Generated by Django 6.0.1 on 2026-02-01 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_monthlyrental_url_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Ocupada'), ('disponible', 'Disponible')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='id_tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rentals.tenant'),
        ),
    ]
