# Generated by Django 6.0.1 on 2026-02-03 00:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_notification_options_alter_obligation_options_and_more'),
        ('rentals', '0004_alter_rental_status_alter_rental_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airbnbrental',
            options={'verbose_name': 'Airbnb Rental', 'verbose_name_plural': 'Airbnb Rentals'},
        ),
        migrations.AlterModelOptions(
            name='monthlyrental',
            options={'verbose_name': 'Monthly Rental', 'verbose_name_plural': 'Monthly Rentals'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-check_in'], 'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
        migrations.AlterModelOptions(
            name='rentalpayment',
            options={'ordering': ['-date'], 'verbose_name': 'Rental Payment', 'verbose_name_plural': 'Rental Payments'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterField(
            model_name='airbnbrental',
            name='is_paid',
            field=models.BooleanField(db_column='is_paid(bool)', default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='monthlyrental',
            name='deposit_amount',
            field=models.DecimalField(db_column='depositAmount', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='monthlyrental',
            name='is_refundable',
            field=models.BooleanField(db_column='is_refundable', default=True, verbose_name='Is Refundable'),
        ),
        migrations.AlterField(
            model_name='monthlyrental',
            name='url_files',
            field=models.FileField(blank=True, db_column='urlFiles', upload_to='', verbose_name='Files URL'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='check_in',
            field=models.DateField(verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='check_out',
            field=models.DateField(verbose_name='Check Out'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='people_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='People Count'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('airbnb', 'Airbnb'), ('daily', 'Daily')], max_length=100, verbose_name='Rental Type'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ocupada', 'Occupied'), ('disponible', 'Available')], default='disponible', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_location',
            field=models.CharField(choices=[('oficina', 'Office'), ('daycare', 'Daycare')], max_length=255, verbose_name='Payment Location'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_method',
            field=models.ForeignKey(db_column='id_paymentMethod', on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='voucher_url',
            field=models.FileField(blank=True, db_column='voucher_url', upload_to='', verbose_name='Voucher URL'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone1',
            field=models.CharField(max_length=20, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone 2'),
        ),
    ]
