# Generated by Django 6.0.1 on 2026-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_airbnbrental_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ocuppied', 'Occupied'), ('available', 'Available')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
