# Generated by Django 6.0.1 on 2026-02-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_location',
            field=models.CharField(choices=[('office', 'Office'), ('daycare', 'Daycare')], max_length=255, verbose_name='Payment Location'),
        ),
    ]
