# Generated by Django 5.2.11 on 2026-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_rentalpayment_payment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='birth_year',
            field=models.IntegerField(default=1990, help_text='Año de nacimiento (ej: 1990)', verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone1',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone 1'),
        ),
    ]
