# Generated by Django 5.2.11 on 2026-02-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_tenant_birth_year_alter_tenant_phone1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('available', 'Available')], default='available', max_length=20, verbose_name='Status'),
        ),
    ]
