# Generated by Django 5.2.11 on 2026-02-13 21:53

import apps.rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrental',
            name='url_files',
            field=models.FileField(blank=True, db_column='urlFiles', upload_to=apps.rentals.models.monthly_rental_files_upload_to, verbose_name='Files URL'),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='voucher_url',
            field=models.FileField(blank=True, db_column='voucher_url', upload_to=apps.rentals.models.rental_payment_voucher_upload_to, verbose_name='Voucher URL'),
        ),
    ]
