# Generated by Django 5.2.11 on 2026-02-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_alter_monthlyrental_url_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_location',
            field=models.CharField(choices=[('office', 'Office'), ('daycare', 'Daycare'), ('online', 'Online')], max_length=255, verbose_name='Payment Location'),
        ),
    ]
