# Generated by Django 5.2.11 on 2026-02-19 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_alter_rentalpayment_payment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnbrental',
            name='deposit_amount',
            field=models.DecimalField(blank=True, db_column='depositAmount', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deposit Amount'),
        ),
        migrations.AddField(
            model_name='airbnbrental',
            name='is_refundable',
            field=models.BooleanField(db_column='is_refundable', default=True, verbose_name='Is Refundable'),
        ),
        migrations.AlterField(
            model_name='airbnbrental',
            name='is_paid',
            field=models.BooleanField(blank=True, db_column='is_paid(bool)', default=False, null=True, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Check Out'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='people_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='People Count'),
        ),
    ]
