# Generated by Django 5.2.11 on 2026-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_airbnbrental_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
