# Generated by Django 5.2.12 on 2026-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_alter_tenant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Amount'),
        ),
    ]
