# Generated by Django 6.0.1 on 2026-01-30 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo')], max_length=100, verbose_name='Condición')),
            ],
            options={
                'verbose_name': 'Enser',
                'verbose_name_plural': 'Enseres',
                'db_table': 'enser',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('use', models.CharField(choices=[('arrendamiento', 'Arrendamiento'), ('personal', 'Personal'), ('comercial', 'Comercial')], max_length=100, verbose_name='Uso')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ubication', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Código postal')),
                ('type_building', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('oficina', 'Oficina')], max_length=100, verbose_name='Tipo de edificio')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('is_deleted', models.DateTimeField(blank=True, db_column='is_deleted', null=True, verbose_name='Fecha de eliminación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'property',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bedrooms', models.IntegerField(verbose_name='Habitaciones')),
                ('bathrooms', models.IntegerField(verbose_name='Baños')),
                ('floors', models.IntegerField(verbose_name='Pisos')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('buildings', models.IntegerField(default=1, verbose_name='Edificios')),
                ('property', models.OneToOneField(db_column='id_property', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='properties.property')),
            ],
            options={
                'verbose_name': 'Detalle de Propiedad',
                'verbose_name_plural': 'Detalles de Propiedades',
                'db_table': 'property_details',
            },
        ),
        migrations.CreateModel(
            name='PropertyLaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255, verbose_name='Nombre de entidad')),
                ('url', models.FileField(blank=True, upload_to='property_laws/', verbose_name='URL del documento')),
                ('original_amount', models.DecimalField(db_column='original_amount', decimal_places=2, max_digits=12, verbose_name='Monto original')),
                ('legal_number', models.CharField(max_length=100, verbose_name='Número legal')),
                ('is_paid', models.BooleanField(db_column='is_paid', default=False, verbose_name='Está pagado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='properties.property')),
            ],
            options={
                'verbose_name': 'Ley de Propiedad',
                'verbose_name_plural': 'Leyes de Propiedades',
                'db_table': 'property_law',
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento')], max_length=50, verbose_name='Tipo de medio')),
                ('url', models.FileField(upload_to='property_media/', verbose_name='URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(db_column='id_property', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
            options={
                'verbose_name': 'Medio de Propiedad',
                'verbose_name_plural': 'Medios de Propiedades',
                'db_table': 'property_media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnserInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_media', models.FileField(blank=True, db_column='url_media', null=True, upload_to='enser_inventory/', verbose_name='Archivos del inventario')),
                ('enser', models.ForeignKey(db_column='id_enser', on_delete=django.db.models.deletion.CASCADE, to='properties.enser')),
                ('property', models.ForeignKey(db_column='id_property', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='properties.property')),
            ],
            options={
                'verbose_name': 'Inventario de Enser',
                'verbose_name_plural': 'Inventarios de Enseres',
                'db_table': 'enser_inventory',
                'unique_together': {('property', 'enser')},
            },
        ),
    ]
