# Generated by Django 6.0.1 on 2026-02-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.FileField(blank=True, help_text='Main property image URL', max_length=500, upload_to='', verbose_name='Featured Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL (src from iframe)', max_length=2000, verbose_name='Google Maps URL'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_deleted',
            field=models.DateTimeField(blank=True, db_column='is_deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_building',
            field=models.CharField(choices=[('Casa', 'House'), ('Apartamento', 'Apartment'), ('Oficina', 'Office')], max_length=100, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ubication',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='use',
            field=models.CharField(choices=[('Arrendamiento', 'Rental'), ('Personal', 'Personal'), ('Comercial', 'Commercial')], max_length=100, verbose_name='Use Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='bathrooms',
            field=models.IntegerField(verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='bedrooms',
            field=models.IntegerField(verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='buildings',
            field=models.IntegerField(default=1, verbose_name='Buildings'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='floors',
            field=models.IntegerField(verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
    ]
