# Generated by Django 6.0.1 on 2026-02-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image_url_property_map_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ubication',
        ),
    ]
