# Generated by Django 6.0.1 on 2026-02-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_ubication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_building',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office')], max_length=100, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='use',
            field=models.CharField(choices=[('rental', 'Rental'), ('personal', 'Personal'), ('commercial', 'Commercial')], max_length=100, verbose_name='Use Type'),
        ),
    ]
