# Generated by Django 6.0.1 on 2026-02-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_type_building_alter_property_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(db_column='state', default='Unknown', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='enser',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=100, verbose_name='Condición'),
        ),
    ]
