# Generated by Django 5.2.11 on 2026-02-13 21:53

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_state_alter_enser_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enserinventory',
            name='url_media',
            field=models.FileField(blank=True, db_column='url_media', null=True, upload_to=apps.properties.models.enser_inventory_upload_to, verbose_name='Archivos del inventario'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.FileField(blank=True, help_text='Main property image URL', max_length=500, upload_to=apps.properties.models.property_image_upload_to, verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='propertylaw',
            name='url',
            field=models.FileField(blank=True, upload_to=apps.properties.models.property_law_upload_to, verbose_name='URL del documento'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='url',
            field=models.FileField(upload_to=apps.properties.models.property_media_upload_to, verbose_name='URL'),
        ),
    ]
