# Generated by Django 5.2.11 on 2026-02-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_enserinventory_url_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('airbnb', 'Airbnb')], help_text='Required if use is rental (monthly or airbnb)', max_length=100, null=True, verbose_name='Rental Type'),
        ),
    ]
