# Generated by Django 5.2.11 on 2026-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='half_bathrooms',
            field=models.IntegerField(default=0, verbose_name='Half Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('airbnb', 'Airbnb')], default='monthly', help_text='Required if use is rental (monthly or airbnb)', max_length=100, null=True, verbose_name='Rental Type'),
        ),
    ]
