# Generated by Django 5.2.11 on 2026-02-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertydetails_half_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='buildings',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Buildings'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='half_bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Half Bathrooms'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='observations',
            field=models.TextField(blank=True, help_text='Additional details about the property', verbose_name='Observations'),
        ),
    ]
