# Generated by Django 5.2.11 on 2026-03-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertydetails_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('airbnb', 'Airbnb')], help_text='Required if use is rental, optional for commercial (monthly or airbnb)', max_length=100, null=True, verbose_name='Rental Type'),
        ),
    ]
