# Generated by Django 5.2.11 on 2026-03-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_rental_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Storage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_building',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office'), ('daycare', 'Daycare')], max_length=100, verbose_name='Building Type'),
        ),
    ]
