# Generated by Django 5.2.11 on 2026-03-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertydetails_storage_alter_property_type_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='storage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Storage'),
        ),
    ]
