# Generated by Django 5.2.11 on 2026-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_propertydetails_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydetails',
            old_name='buildings',
            new_name='storages',
        ),
    ]
