# Generated by Django 5.2.11 on 2026-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_propertydetails_buildings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='storages',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Storages'),
        ),
    ]
