# Generated by Django 5.2.11 on 2026-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_propertydetails_storages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydetails',
            old_name='storage',
            new_name='buildings',
        ),  
    ]
