# Generated by Django 5.2.11 on 2026-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_remove_propertydetails_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='buildings',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Buildings'),
        ),
    ]
