# Generated by Django 5.2.12 on 2026-03-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_propertydetails_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_building',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office'), ('daycare', 'Daycare'), ('land', 'Land')], max_length=100, verbose_name='Building Type'),
        ),
    ]
