# Generated by Django 5.2.12 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_property_type_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylaw',
            name='is_paid',
            field=models.BooleanField(blank=True, db_column='is_paid', default=False, null=True, verbose_name='Está pagado'),
        ),
        migrations.AlterField(
            model_name='propertylaw',
            name='original_amount',
            field=models.DecimalField(blank=True, db_column='original_amount', decimal_places=2, max_digits=12, null=True, verbose_name='Monto original'),
        ),
    ]
