# Generated by Django 5.2.12 on 2026-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_propertylaw_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylaw',
            name='legal_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número legal'),
        ),
    ]
