# Generated by Django 6.0.1 on 2026-01-31 00:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Obligación',
                'verbose_name_plural': 'Tipos de Obligaciones',
                'db_table': 'obligation_type',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255, verbose_name='Nombre de entidad')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('temporality', models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual'), ('one_time', 'Una vez')], max_length=100, verbose_name='Temporalidad')),
                ('property', models.ForeignKey(db_column='id_property', on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='properties.property')),
                ('obligation_type', models.ForeignKey(db_column='id_obligation_type', on_delete=django.db.models.deletion.PROTECT, to='finance.obligationtype', verbose_name='Tipo de obligación')),
            ],
            options={
                'verbose_name': 'Obligación',
                'verbose_name_plural': 'Obligaciones',
                'db_table': 'obligation',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha de pago')),
                ('voucher_url', models.URLField(blank=True, db_column='voucher_url', verbose_name='URL del comprobante')),
                ('obligation', models.ForeignKey(db_column='id_obligation', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.obligation', verbose_name='Obligación')),
                ('payment_method', models.ForeignKey(db_column='id_paymentMethod', on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Pago de Obligación',
                'verbose_name_plural': 'Pagos de Obligaciones',
                'db_table': 'property_payment',
                'ordering': ['-date'],
            },
        ),
    ]
