# Generated by Django 5.2.5 on 2026-01-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='temporality',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual'), ('one_time', 'Una vez'), ('weekly', 'Semanal')], max_length=100, verbose_name='Temporalidad'),
        ),
        migrations.AlterField(
            model_name='obligationtype',
            name='name',
            field=models.CharField(choices=[('tax', 'Impuesto'), ('seguro', 'Seguro'), ('cuota', 'Cuota')], max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
