# Generated by Django 6.0.1 on 2026-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_obligation_temporality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypayment',
            name='voucher_url',
            field=models.FileField(blank=True, db_column='voucher_url', upload_to='', verbose_name='URL del comprobante'),
        ),
    ]
