# Generated by Django 6.0.1 on 2026-02-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_populate_obligation_types'),
        ('finance', '0004_notification'),
    ]

    operations = [
    ]
