# Generated by Django 6.0.1 on 2026-02-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_merge_20260201_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('card', 'Tarjeta')], max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='payment_method',
            field=models.ForeignKey(db_column='id_payment_method', on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Método de pago'),
        ),
    ]
