# Generated by Django 6.0.1 on 2026-02-03 00:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_populate_payment_methods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='obligation',
            options={'ordering': ['-due_date'], 'verbose_name': 'Obligation', 'verbose_name_plural': 'Obligations'},
        ),
        migrations.AlterModelOptions(
            name='obligationtype',
            options={'verbose_name': 'Obligation Type', 'verbose_name_plural': 'Obligation Types'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='propertypayment',
            options={'ordering': ['-date'], 'verbose_name': 'Obligation Payment', 'verbose_name_plural': 'Obligation Payments'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('obligation_due', 'Obligation Due'), ('rental_ending', 'Rental Ending'), ('payment_overdue', 'Payment Overdue'), ('repair_scheduled', 'Repair Scheduled'), ('system', 'System')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='entity_name',
            field=models.CharField(max_length=255, verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='obligation_type',
            field=models.ForeignKey(db_column='id_obligation_type', on_delete=django.db.models.deletion.PROTECT, to='finance.obligationtype', verbose_name='Obligation Type'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='temporality',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual'), ('one_time', 'One Time'), ('weekly', 'Weekly')], max_length=100, verbose_name='Temporality'),
        ),
        migrations.AlterField(
            model_name='obligationtype',
            name='name',
            field=models.CharField(choices=[('tax', 'Tax'), ('seguro', 'Insurance'), ('cuota', 'Fee')], max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('check', 'Check'), ('card', 'Card')], max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='obligation',
            field=models.ForeignKey(db_column='id_obligation', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.obligation', verbose_name='Obligation'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='payment_method',
            field=models.ForeignKey(db_column='id_payment_method', on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='voucher_url',
            field=models.FileField(blank=True, db_column='voucher_url', upload_to='', verbose_name='Voucher URL'),
        ),
    ]
