# Generated by Django 6.0.1 on 2026-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_notification_options_alter_obligation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypayment',
            name='payment_location',
            field=models.CharField(choices=[('office', 'Office'), ('daycare', 'Daycare')], default='office', max_length=255, verbose_name='Payment Location'),
        ),
    ]
