# Generated by Django 5.2.11 on 2026-02-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_propertypayment_payment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('check', 'Check'), ('card', 'Card'), ('zelle', 'Zelle')], max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='propertypayment',
            name='payment_location',
            field=models.CharField(choices=[('office', 'Office'), ('daycare', 'Daycare'), ('online', 'Online')], default='online', max_length=255, verbose_name='Payment Location'),
        ),
    ]
