# Generated by Django 5.2.11 on 2026-02-13 21:53

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_paymentmethod_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypayment',
            name='voucher_url',
            field=models.FileField(blank=True, db_column='voucher_url', upload_to=apps.finance.models.property_payment_voucher_upload_to, verbose_name='Voucher URL'),
        ),
    ]
