# Generated by Django 5.2.11 on 2026-02-13 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_zelle_payment_method'),
        ('finance', '0011_alter_propertypayment_voucher_url'),
    ]

    operations = [
    ]
