# Generated by Django 5.2.11 on 2026-02-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_merge_20260213_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationtype',
            name='name',
            field=models.CharField(choices=[('tax', 'Tax'), ('insurance', 'Insurance'), ('fee', 'Fee')], max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
