# Generated by Django 5.2.12 on 2026-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_obligationtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('check', 'Check'), ('card', 'Card'), ('zelle', 'Zelle'), ('checking account', 'Checking Account')], max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
