# Generated by Django 5.2.12 on 2026-04-04 00:57

import apps.vehicles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0014_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationVehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('tax', 'Tax'), ('insurance', 'Insurance')], max_length=255, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('commercial', 'Commercial'), ('sport', 'Sport'), ('permanent_use', 'Permanent Use'), ('water', 'Water')], max_length=30)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.vehicles.models.vehicle_photo_upload_to)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('responsible', models.ManyToManyField(blank=True, related_name='vehicles', to='vehicles.responsible')),
            ],
        ),
        migrations.CreateModel(
            name='ObligationVehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Entity Name')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temporality', models.CharField(choices=[('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual'), ('one_time', 'One Time'), ('weekly', 'Weekly')], max_length=100, verbose_name='Temporality')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.vehicles.models.vehicle_doc_upload_to)),
                ('obligation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations_vehicle_type', to='vehicles.obligationvehicletype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_vehicle', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.vehicles.models.vehicle_doc_upload_to)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.vehicles.models.vehicle_photo_upload_to)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher', models.FileField(blank=True, null=True, upload_to=apps.vehicles.models.vehicle_payment_voucher_upload_to)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vehicles.obligationvehicle')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRepair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='vehicles.vehicle')),
            ],
        ),
    ]
