# Generated by Django 5.2.12 on 2026-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepair',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
