# Generated by Django 5.2.12 on 2026-04-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclerepair_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='driver',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='responsible',
            field=models.ManyToManyField(blank=True, null=True, related_name='vehicles', to='vehicles.responsible'),
        ),
       
    ]
