# Generated by Django 5.2.12 on 2026-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_owner_vehicle_driver_vehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationvehicle',
            name='temporality',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('semiannual', 'Semiannual'), ('annual', 'Annual'), ('one_time', 'One Time'), ('weekly', 'Weekly')], max_length=100, verbose_name='Temporality'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('sport', 'Sport'), ('personal', 'Personal'), ('non_permanent_use', 'Non Permanent Use'), ('permanent_use', 'Permanent Use'), ('water', 'Water')], max_length=30),
        ),
    ]
