# Generated by Django 5.2.11 on 2026-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('cliente', 'Client'), ('invitado', 'Guest')], max_length=50, unique=True),
        ),
    ]
