# Generated by Django 6.0.1 on 2026-01-30 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('observation', models.TextField(blank=True, verbose_name='Observación')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('property', models.ForeignKey(db_column='id_property', on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='properties.property')),
            ],
            options={
                'verbose_name': 'Reparación',
                'verbose_name_plural': 'Reparaciones',
                'db_table': 'repair',
                'ordering': ['-date'],
            },
        ),
    ]
