# Generated by Django 5.2.11 on 2026-02-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('alert_type', models.CharField(choices=[('5_days', '5 Days Before'), ('1_day', '1 Day Before'), ('same_day', 'Same Day')], max_length=20, verbose_name='Alert Type')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Alert Sent',
                'verbose_name_plural': 'Alerts Sent',
                'db_table': 'alert_sent',
                'ordering': ['-sent_at'],
                'unique_together': {('content_type', 'object_id', 'alert_type')},
            },
        ),
    ]
